# Generated by Django 4.2.7 on 2026-04-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
