# Generated by Django 4.2.7 on 2026-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_skill_category_skill_user_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
