import io
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

def generate_resume_report(analysis_data, student_name):
    """
    Generates a professional DOCX report from resume analysis data.
    """
    doc = Document()

    # ── Header Section ────────────────────────────────────────────────────────
    header = doc.add_section().header
    htable = header.add_table(1, 2, width=Inches(6))
    htable.rows[0].cells[0].text = "Smart Placement Platform"
    htable.rows[0].cells[1].text = f"Date: {datetime.now().strftime('%Y-%m-%d')}"
    
    # ── Title ────────────────────────────────────────────────────────────────
    title = doc.add_heading("Resume Intelligence & Hiring Verdict", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Candidate Info ───────────────────────────────────────────────────────
    doc.add_heading("Candidate Overview", level=1)
    p = doc.add_paragraph()
    p.add_run("Candidate Name: ").bold = True
    p.add_run(student_name)
    
    p = doc.add_paragraph()
    p.add_run("Target Role: ").bold = True
    p.add_run(analysis_data.get("recommended_role", "Not Specified"))

    p = doc.add_paragraph()
    p.add_run("Experience Level: ").bold = True
    p.add_run(analysis_data.get("experience_level", "Entry"))

    # ── Scores & Verdict ─────────────────────────────────────────────────────
    doc.add_heading("Hiring Metrics", level=1)
    
    table = doc.add_table(rows=1, cols=3)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Metric'
    hdr_cells[1].text = 'Score'
    hdr_cells[2].text = 'Verdict'
    
    row_cells = table.add_row().cells
    row_cells[0].text = "Resume IQ"
    row_cells[1].text = f"{analysis_data.get('score', 0)}%"
    row_cells[2].text = analysis_data.get("final_verdict", "N/A")
    
    row_cells = table.add_row().cells
    row_cells[0].text = "ATS Optimization"
    row_cells[1].text = f"{analysis_data.get('ats_score', 0)}%"
    row_cells[2].text = "Calculated"

    row_cells = table.add_row().cells
    row_cells[0].text = "AI Confidence"
    row_cells[1].text = f"{analysis_data.get('ai_confidence', 0)}%"
    row_cells[2].text = "High"

    # ── Summary ──────────────────────────────────────────────────────────────
    doc.add_heading("Executive Summary", level=2)
    doc.add_paragraph(analysis_data.get("summary", "No summary available."))

    # ── Critical Blockers ───────────────────────────────────────────────────
    blockers = analysis_data.get("critical_blockers", [])
    if blockers:
        doc.add_heading("Critical Blockers (Immediate Action Required)", level=1)
        for b in blockers:
            issue = b.get("issue", b) if isinstance(b, dict) else b
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(issue).font.color.rgb = RGBColor(0xFF, 0x00, 0x00)

    # ── Improvement Suggestions ─────────────────────────────────────────────
    suggestions = analysis_data.get("suggestions", [])
    if suggestions:
        doc.add_heading("Actionable Improvement Plan", level=2)
        for s in suggestions:
            doc.add_paragraph(s, style='List Number')

    # ── Skill Analysis ───────────────────────────────────────────────────────
    doc.add_heading("Skill Profile", level=2)
    skills = analysis_data.get("skills", [])
    missing = analysis_data.get("missing_skills", [])
    
    p = doc.add_paragraph()
    p.add_run("Verified Skills: ").bold = True
    p.add_run(", ".join(skills) if skills else "None detected")
    
    p = doc.add_paragraph()
    p.add_run("Missing Critical Skills: ").bold = True
    p.add_run(", ".join(missing) if missing else "None identified")

    # ── Footer ───────────────────────────────────────────────────────────────
    doc.add_paragraph("\n")
    footer = doc.add_paragraph("Generated by Smart Placement AI Intelligence Engine.")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.style.font.size = Pt(8)
    footer.style.font.italic = True

    # Save to memory
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream
